[package]
name = "portable-daemon"
version = "19.9.9"
edition = "2024"
authors = ["Kimiblock"]
rust-version = "1.97"
documentation = "https://github.com/Kraftland/portable"
description = "Fast, private, modern sandbox designed for desktop Linux"
repository = "https://github.com/Kraftland/portable"
license = "GPL-3.0-or-later"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
portable_legacy_conf = { version = "1.0.0", path = "./lib/legacy_conf" }
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "sync", "signal", "fs", "io-util"] }
tokio-util = { version = "0.7.18", features = ["rt"] }
nix = { version = "0.31.3", features = ["term", "user", "ioctl"] }
jiff = { version = "0.2.34", features = ["std"], default-features = false }
toml = { version = "1.1.3", features = ["parse", "serde"], default-features = false }
zbus = { version = "5.18.0", features = ["async-executor", "async-fs", "async-io", "async-lock", "async-process", "async-task", "tokio"], default-features = false }

command-fds = { version = "0.3.3", features = ["tokio"] }

# systemd
zbus_systemd = { version = "0.26100.0", features = ["systemd1"], default-features = false, optional = true }

# Wayland
wayrs-protocols = { version = "0.14.11", features = ["security-context-v1"] , optional = true }
wayrs-client = { version = "1.3.1", features = ["tokio"], optional = true }

# Devices
udev = { version = "0.9.3", features = ["send", "sync"], default-features = false, optional = true }

[workspace]
resolver = "3"
members = ["lib/legacy_conf"]
exclude = ["lib/init"]

[features]
default	= ["systemd", "flatpak", "pulseaudio", "x11", "wayland", "gpu", "camera", "input"]

# Audio support metaflag
audio	= []
# Build with PulseAudio support, with server address parsing and binding.
# This flag serves as an implementation for the audio subsystem.
pulseaudio = ["audio"]

# Devices support metaflag
devices	= ["dep:udev"]
# Build with GPU bindings support
gpu	= ["devices"]
# Build with Camera bindings support
camera	= ["devices"]
# Build with Input bindings support
input	= ["devices"]

# Build with systemd support, note that non-systemd mode does not work yet
systemd	= ["dep:zbus_systemd"]

# Display support metaflag
display	= []
# Build with X11 display protocol support, this includes real X11 display or XWayland
x11	= ["display"]
# Build with Wayland display protocol support
wayland	= ["dep:wayrs-client", "dep:wayrs-protocols", "display"]

# Mimic Flatpak to host, required until appd lands
flatpak = []
