#!/usr/bin/bash

# This is your Application ID, avoid conflict
appID="top.kimiblock.example"

# This is a friendly name of an application. It should only contain ASCII characters and not spaces.
friendlyName="Portable_Test"

# This is the state directory of your application, which is located under "XDG_DATA_HOME"
stateDirectory="Portable_Test_Data"

# This is the target executable to launch
launchTarget="glxgears"

# Takes boolean value. When enabled, do not process XAuth files and enable X access. Generally this should be always on.
waylandOnly="false"