#!/usr/bin/bash

# This is your Application ID, avoid conflict
appID=""

# This is a friendly name of an application. It should only contain ASCII characters and not spaces.
friendlyName=""

stateDirectory=""
