#!/usr/bin/bash
echo "Acting as flatpak-spawn..."
while [[ $(echo "$1" | cut -c 1-1) = "-" ]]; do
	shift
done
if [[ $1 = "prlimit" ]]; then
	shift
	while [[ $(echo "$1" | cut -c 1-1) = "-" ]]; do
		shift
	done
fi
echo "Decoded cmdline: $@"
$@
exit $?