name: Build submodule Open NG

on:
  release:
    types: released
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'lib/open-ng/go.mod'

    - name: Initialise submodules
      run: git submodule update --init --recursive

    - name: Build
      run: |
        cd lib/open-ng
        go build