# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Test on PR and Release

on:
  release:
    types: released
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'lib/daemon/go.mod'
    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y libnotify4 libudev-dev zenity xdg-dbus-proxy systemd dbus grep xdg-desktop-portal xdg-desktop-portal-gtk bubblewrap

    - name: Build Daemon
      run: bash lib/build.sh

    - name: Install Portable
      run: sudo bash lib/package.sh

    - name: Install Compositor
      run: sudo apt install -y weston

    - name: Start Compositor
      run: |
          weston -B headless
          for i in {1..20}; do
            sleep 0.5
            if [ -S "$XDG_RUNTIME_DIR/wayland-0" ]; then
              echo "Weston ready"
              break
            fi
          done

    - name: Test daemon
      run: go test -v ./...
      working-directory: 'lib/daemon'
    - name: Test helper
      run: go test -v ./...
      working-directory: 'lib/helper'
    - name: Test open
      run: go test -v ./...
      working-directory: 'lib/open-ng'
    - name: Test flatpak-spawn
      run: go test -v ./...
      working-directory: 'lib/flatpak-spawn-stub'
    - name: Test prlimit
      run: go test -v ./...
      working-directory: 'lib/prlimit-stub'
